// lib/moddulo/attachments.ts
// Shared text extraction for Moddulo chat attachments.
// Used by the chat API route and the PESTEL import endpoint.

import { anthropic } from "@/lib/ai/claude";
import { adminStorage } from "@/lib/firebase-admin";
import type { ChatAttachment } from "@/types/moddulo.types";

const CLAUDE_MODEL = "claude-sonnet-4-6";

// Closed set of error placeholders generated by extractTextPerFile.
// Use isExtractionError() instead of generic startsWith("[") checks to avoid
// false positives on valid documents that open with bracket notation.
export const EXTRACTION_ERROR_PREFIXES = [
  "[No se pudo acceder a",
  "[Archivo no soportado:",
  "[Error procesando archivo]",
] as const;

export function isExtractionError(text: string): boolean {
  const t = text.trimStart();
  return EXTRACTION_ERROR_PREFIXES.some((prefix) => t.startsWith(prefix));
}

export async function extractTextPerFile(attachment: ChatAttachment): Promise<string> {
  let buffer: Buffer;

  if (attachment.storagePath) {
    // Admin SDK download — bypasses Storage rules and GCP uniform bucket-level access
    try {
      const [data] = await adminStorage.bucket().file(attachment.storagePath).download();
      buffer = data as Buffer;
    } catch {
      return `[No se pudo acceder a ${attachment.nombre}]`;
    }
  } else {
    const res = await fetch(attachment.url);
    if (!res.ok) return `[No se pudo acceder a ${attachment.nombre}]`;
    buffer = Buffer.from(await res.arrayBuffer());
  }

  // Resolve effective MIME — some browsers send application/octet-stream for DOCX
  const ext = attachment.nombre.split(".").pop()?.toLowerCase() ?? "";
  const mimeType =
    attachment.tipo === "application/octet-stream" && (ext === "docx" || ext === "doc")
      ? "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
      : attachment.tipo;

  if (mimeType === "application/pdf") {
    try {
      // eslint-disable-next-line @typescript-eslint/no-require-imports
      const pdfParse = require("pdf-parse") as (buf: Buffer) => Promise<{ text: string }>;
      const result = await pdfParse(buffer);
      const text = result.text.trim();
      if (text.length >= 120) return `[Archivo: ${attachment.nombre}]\n${text}`;
    } catch { /* fall through to Claude Vision */ }
    const base64 = buffer.toString("base64");
    const msg = await anthropic.messages.create({
      model: CLAUDE_MODEL,
      max_tokens: 2048,
      messages: [{ role: "user", content: [
        { type: "document", source: { type: "base64", media_type: "application/pdf", data: base64 } },
        { type: "text", text: "Extrae toda la información relevante de este documento de forma estructurada." },
      ]}],
    });
    const block = msg.content[0];
    return `[Archivo: ${attachment.nombre}]\n${block.type === "text" ? block.text : ""}`;
  }

  if (mimeType.includes("wordprocessingml") || mimeType === "application/msword") {
    const mammoth = await import("mammoth");
    const result = await mammoth.extractRawText({ buffer });
    return `[Archivo: ${attachment.nombre}]\n${result.value}`;
  }

  if (mimeType.startsWith("text/") || mimeType === "text/csv") {
    return `[Archivo: ${attachment.nombre}]\n${buffer.toString("utf-8")}`;
  }

  if (mimeType.startsWith("image/")) {
    const validImageTypes = ["image/jpeg", "image/png", "image/gif", "image/webp"] as const;
    type ImageMediaType = typeof validImageTypes[number];
    const mediaType: ImageMediaType = validImageTypes.includes(mimeType as ImageMediaType)
      ? (mimeType as ImageMediaType)
      : "image/jpeg";
    const base64 = buffer.toString("base64");
    const msg = await anthropic.messages.create({
      model: CLAUDE_MODEL,
      max_tokens: 1024,
      messages: [{ role: "user", content: [
        { type: "image", source: { type: "base64", media_type: mediaType, data: base64 } },
        { type: "text", text: "Describe el contenido de esta imagen. Si hay texto, transcríbelo. Si hay datos o tablas, descríbelos con precisión." },
      ]}],
    });
    const block = msg.content[0];
    return `[Imagen: ${attachment.nombre}]\n${block.type === "text" ? block.text : ""}`;
  }

  return `[Archivo no soportado: ${attachment.nombre}]`;
}
