// lib/moddulo/attachments.ts
// Shared text extraction for chat attachments.
// Consumers (6): app/api/moddulo/chat/[phaseId], import-moddulo-attachments,
// f3/confirm, f3/canal1/entregar, f3/canal3/vincular, and
// app/api/fontana/sesion/[sesionId]/adjunto.
// extractTextPerFile() resolves the bytes from Storage/URL; the Fontana
// attachment route already has the bytes in memory and calls
// extractTextFromBuffer() directly (it never persists a binary anywhere).

import { anthropic } from "@/lib/ai/claude";
import { adminStorage } from "@/lib/firebase-admin";
import type { ChatAttachment } from "@/types/moddulo.types";

const CLAUDE_MODEL = "claude-sonnet-4-6";

// Closed set of error placeholders generated by the extractor.
// Use isExtractionError() instead of generic startsWith("[") checks to avoid
// false positives on valid documents that open with bracket notation.
export const EXTRACTION_ERROR_PREFIXES = [
  "[No se pudo acceder a",
  "[Archivo no soportado:",
  "[Error procesando archivo]",
] as const;

export function isExtractionError(text: string): boolean {
  const t = text.trimStart();
  return EXTRACTION_ERROR_PREFIXES.some((prefix) => t.startsWith(prefix));
}

const DOCX_MIME =
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
const XLSX_MIME =
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";

/**
 * Resolve the effective MIME type. Some browsers send
 * application/octet-stream for Office files, so fall back to the extension.
 */
export function resolveEffectiveMime(tipo: string, nombre: string): string {
  if (tipo && tipo !== "application/octet-stream") return tipo;
  const ext = nombre.split(".").pop()?.toLowerCase() ?? "";
  if (ext === "docx" || ext === "doc") return DOCX_MIME;
  if (ext === "xlsx" || ext === "xls") return XLSX_MIME;
  if (ext === "pdf") return "application/pdf";
  if (ext === "csv") return "text/csv";
  if (ext === "json") return "application/json";
  if (ext === "md" || ext === "txt") return "text/plain";
  return tipo;
}

/**
 * Extract readable text from an in-memory file buffer. Pure function over
 * (buffer, mime, name) — no network fetch of the file itself, no persistence.
 * PDF/image branches still call Claude for OCR/vision fallback.
 */
export async function extractTextFromBuffer(
  buffer: Buffer,
  mimeType: string,
  nombre: string
): Promise<string> {
  if (mimeType === "application/pdf") {
    try {
      // eslint-disable-next-line @typescript-eslint/no-require-imports
      const pdfParse = require("pdf-parse") as (
        buf: Buffer
      ) => Promise<{ text: string }>;
      const result = await pdfParse(buffer);
      const text = result.text.trim();
      if (text.length >= 120) return `[Archivo: ${nombre}]\n${text}`;
    } catch {
      /* fall through to Claude Vision */
    }
    const base64 = buffer.toString("base64");
    const msg = await anthropic.messages.create({
      model: CLAUDE_MODEL,
      max_tokens: 2048,
      messages: [
        {
          role: "user",
          content: [
            {
              type: "document",
              source: { type: "base64", media_type: "application/pdf", data: base64 },
            },
            {
              type: "text",
              text: "Extrae toda la información relevante de este documento de forma estructurada.",
            },
          ],
        },
      ],
    });
    const block = msg.content[0];
    return `[Archivo: ${nombre}]\n${block.type === "text" ? block.text : ""}`;
  }

  if (mimeType.includes("wordprocessingml") || mimeType === "application/msword") {
    const mammoth = await import("mammoth");
    const result = await mammoth.extractRawText({ buffer });
    return `[Archivo: ${nombre}]\n${result.value}`;
  }

  // XLSX / XLS (2026-09-01) — el usuario suele traer su lista de preguntas
  // de indicadores en hoja de cálculo. exceljs (no SheetJS: el paquete npm
  // `xlsx` está desactualizado con advisories). Cada hoja se vuelca a texto
  // tabular (filas separadas por \n, celdas por \t).
  if (
    mimeType === XLSX_MIME ||
    mimeType === "application/vnd.ms-excel" ||
    mimeType.includes("spreadsheetml")
  ) {
    const ExcelJS = (await import("exceljs")).default;
    const wb = new ExcelJS.Workbook();
    // exceljs empaqueta un @types/node viejo cuyo `Buffer` no cuadra con el
    // del proyecto; el Buffer real de Node funciona en runtime.
    await wb.xlsx.load(buffer as unknown as ArrayBuffer);
    const partes: string[] = [];
    wb.eachSheet((sheet) => {
      const filas: string[] = [];
      sheet.eachRow({ includeEmpty: false }, (row) => {
        const celdas = (row.values as unknown[])
          .slice(1) // exceljs indexa desde 1; values[0] siempre es undefined
          .map((v) => {
            if (v === null || v === undefined) return "";
            if (typeof v === "object" && "text" in (v as Record<string, unknown>)) {
              return String((v as { text: unknown }).text ?? "");
            }
            if (typeof v === "object" && "result" in (v as Record<string, unknown>)) {
              return String((v as { result: unknown }).result ?? "");
            }
            return String(v);
          });
        if (celdas.some((c) => c.trim() !== "")) filas.push(celdas.join("\t"));
      });
      if (filas.length > 0) partes.push(`# ${sheet.name}\n${filas.join("\n")}`);
    });
    return `[Archivo: ${nombre}]\n${partes.join("\n\n")}`;
  }

  if (
    mimeType.startsWith("text/") ||
    mimeType === "text/csv" ||
    mimeType === "application/json"
  ) {
    return `[Archivo: ${nombre}]\n${buffer.toString("utf-8")}`;
  }

  if (mimeType.startsWith("image/")) {
    const validImageTypes = ["image/jpeg", "image/png", "image/gif", "image/webp"] as const;
    type ImageMediaType = typeof validImageTypes[number];
    const mediaType: ImageMediaType = validImageTypes.includes(mimeType as ImageMediaType)
      ? (mimeType as ImageMediaType)
      : "image/jpeg";
    const base64 = buffer.toString("base64");
    const msg = await anthropic.messages.create({
      model: CLAUDE_MODEL,
      max_tokens: 1024,
      messages: [
        {
          role: "user",
          content: [
            { type: "image", source: { type: "base64", media_type: mediaType, data: base64 } },
            {
              type: "text",
              text: "Describe el contenido de esta imagen. Si hay texto, transcríbelo. Si hay datos o tablas, descríbelos con precisión.",
            },
          ],
        },
      ],
    });
    const block = msg.content[0];
    return `[Imagen: ${nombre}]\n${block.type === "text" ? block.text : ""}`;
  }

  return `[Archivo no soportado: ${nombre}]`;
}

export async function extractTextPerFile(attachment: ChatAttachment): Promise<string> {
  let buffer: Buffer;

  if (attachment.storagePath) {
    // Admin SDK download — bypasses Storage rules and GCP uniform bucket-level access
    try {
      const [data] = await adminStorage.bucket().file(attachment.storagePath).download();
      buffer = data as Buffer;
    } catch {
      return `[No se pudo acceder a ${attachment.nombre}]`;
    }
  } else {
    const res = await fetch(attachment.url);
    if (!res.ok) return `[No se pudo acceder a ${attachment.nombre}]`;
    buffer = Buffer.from(await res.arrayBuffer());
  }

  const mimeType = resolveEffectiveMime(attachment.tipo, attachment.nombre);
  return extractTextFromBuffer(buffer, mimeType, attachment.nombre);
}
